# Generated by Django 5.0.14 on 2026-09-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_recalled',
            field=models.BooleanField(default=False, help_text='Mark whether the message has been recalled'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='recalled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when message was recalled', null=True),
        ),
    ]
